iron_bank/iron_bank/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from iron_bank_api.views import IndexView, UserCreateView, TransactionCreateView, TransactionListCreateAPIView, TransactionDetailAPIView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^obtain_token/$', obtain_auth_token),
    url(r'^create_user/$', UserCreateView.as_view(), name='user_create_view'),
    url(r'^$', IndexView, name="index_view"),
    url(r'^transactions/$', TransactionCreateView.as_view(), name="transaction_create_view"),
    url(r'^api/transactions/$', TransactionListCreateAPIView.as_view(), name="transaction_list_create_api_view"),
    url(r'^api/transactions/(?P<pk>\d+)/$', TransactionDetailAPIView.as_view(), name="transaction_detail_api_view"),
]

iron_bank/iron_bank_api/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from rest_framework.authtoken.models import Token


PROCESS_TYPE = {
    ("D","Deposit"),
    ("W","Withdrawal"),
}

class Transaction(models.Model):
    account = models.ForeignKey('auth.User')
    amount = models.FloatField(default=0)
    process_type = models.CharField(max_length=1, choices=PROCESS_TYPE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']


@receiver(post_save, sender='auth.User')
def create_user_profile(**kwargs):
    created = kwargs.get('created')
    instance = kwargs.get('instance')
    if created:
        Profile.objects.create(account=instance)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
   if created:
       Token.objects.create(user=instance)


class Profile(models.Model):
    account = models.OneToOneField('auth.User')

    @property
    def balance(self):
        deposit = 0
        withdraw = 0
        all_transactions = Transaction.objects.filter(account=self.account)
        for transaction in all_transactions:
            if transaction.process_type == 'W':
                withdraw += transaction.amount
            else:
                deposit += transaction.amount
        return round(deposit - withdraw, 2)

iron_bank/iron_bank_api/views.py
from django.shortcuts import render
from iron_bank_api.models import Transaction, Profile
from iron_bank_api.serializers import TransactionSerializer
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from rest_framework.generics import ListCreateAPIView, RetrieveAPIView
from django.contrib.auth.forms import User
from django.urls import reverse_lazy
from rest_framework.permissions import IsAuthenticated
from django.core.exceptions import ValidationError


class UserCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("index_view")


def IndexView(request):
    context = {
        "all_transactions": Transaction.objects.all(),
    }
    return render(request, 'index.html', context)


class TransactionCreateView(CreateView):
    model = Transaction
    success_url = reverse_lazy("transaction_create_view")
    fields = ('amount', 'process_type')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["transaction_list"] = Transaction.objects.filter(account=self.request.user)
        context["profile_list"] = Profile.objects.filter(account=self.request.user)
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.account = self.request.user
        if instance.process_type == "W" and instance.amount > instance.account.profile.balance:
                return super().form_invalid(form)
        return super().form_valid(form)


class TransactionListCreateAPIView(ListCreateAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = TransactionSerializer

    def get_queryset(self):
        return Transaction.objects.filter(account=self.request.user)

    def perform_create(self, serializer):
        process_type = serializer.validated_data["process_type"]
        amount = serializer.validated_data["amount"]
        if process_type == "W" and amount > self.request.user.profile.balance:
            raise ValidationError("You have insufficient funds.")
        serializer.save(account=self.request.user)
        return super().perform_create(serializer)



class TransactionDetailAPIView(RetrieveAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = TransactionSerializer
    def get_queryset(self):
        return Transaction.objects.filter(account=self.request.user)

iron_bank/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Iron Bank</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen" title="no title">
    <style media="screen">
      body {
        background-color: #bea63a;
      }
    </style>
  </head>
  <body>
  <nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="nav navbar-nav">
      <div class="navbar-header">
         <img alt="Brand" src="{% static 'ironbank.jpg' %}" height="50" width="50">
      </div>
      <li><a href="{% url 'user_create_view' %}">Create User</a></li>
        {% if not request.user.is_authenticated %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
            <li><a href="{% url 'logout' %}?next={% url 'index_view' %}">Logout</a></li>
            <p class="navbar-text">Hello, <b>{{ request.user }}</b></p>
        {% endif %}
    </div>
  </div>
  </nav>
    <div class="container">
    {% block content %}

    {% endblock %}
    </div>
  </body>
</html>

iron_bank/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% if not request.user.is_authenticated %}
  <h1>Welcome to The Iron Bank of Braavos</h1>
  <h1>Log in to Continue Banking</h1>
{% else %}
  <a href="{% url 'transaction_create_view' %}"><h1>Go to Account Transactions</h1></a>
{% endif %}
{% endblock %}

iron_bank/templates/iron_bank_api/transaction_form.html
{% extends 'base.html' %}

{% block content %}

{% if request.user.is_authenticated %}
<div class="row">
  <div class="col-md-5">
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-body">
          <form class="" action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" class="btn btn-default" value="Submit">
          </form>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-body">
          <h1>Balance: ${{ request.user.profile.balance|floatformat:2 }}</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-1">
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-hover table-condensed">
          <tr>
            <th>Amount</th>
            <th>Deposit/Withdrawal</th>
            <th>Date</th>
          </tr>
          {% for transaction in transaction_list %}
          <tr>
            <td>${{ transaction.amount|floatformat:2 }}</td>
            <td>{{ transaction.get_process_type_display }}</td>
            <td>{{ transaction.created }}</td>
          </tr>
        {% endfor %}
        </table>
      </div>
    </div>
  </div>
  {% else %}
    <h1>Log in to continue banking</h1>
</div>
{% endif %}



{% endblock %}

iron_bank/templates/search/search.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}